# Mathematic Opretion Using Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(1,10).reshape(3,3)
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# add()

In [4]:
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# subtract()

In [7]:
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# divide()

In [8]:
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# multiply()

In [9]:
np.multiply(array1,array2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
array1 @ array2 # matrix production matiply

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# dot()

In [11]:
array1.dot(array2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# max()

In [15]:
array1.max()

9

# argmax()

In [30]:
array1.argmax()

8

# min()

In [17]:
array1.min()

1

In [18]:
 array1.max(axis = 0) # 0 = coloumn

array([7, 8, 9])

In [19]:
 array1.max(axis = 1) # 1 = row

array([3, 6, 9])

# sum()

In [20]:
np.sum(array1)

45

In [21]:
np.sum(array1, axis = 0)

array([12, 15, 18])

In [22]:
np.sum(array1, axis = 1)

array([ 6, 15, 24])

# mean()

In [23]:
np.mean(array1) # foe find element evrage

5.0

# sqrt()

In [24]:
np.sqrt(array1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# std()

In [25]:
np.std(array1)

2.581988897471611

# exp()

In [26]:
np.exp(array1) # exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# log()

In [27]:
np.log(array1) # we can use as log10 as log10,11 etc...

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])